// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "../types.ts";

export const XAI_OAUTH_MODELS = {
	"grok-4.5": {
		id: "grok-4.5",
		name: "Grok 4.5",
		api: "openai-codex-responses",
		provider: "xai-oauth",
		baseUrl: "https://api.x.ai/v1",
		reasoning: true,
		thinkingLevelMap: {"off":null,"minimal":null,"xhigh":null},
		input: ["text", "image"],
		cost: {
			input: 2,
			output: 6,
			cacheRead: 0.5,
			cacheWrite: 0,
		},
		contextWindow: 500000,
		maxTokens: 500000,
	} satisfies Model<"openai-codex-responses">,
	"grok-composer-2.5-fast": {
		id: "grok-composer-2.5-fast",
		name: "Grok Composer 2.5 Fast",
		api: "openai-codex-responses",
		provider: "xai-oauth",
		baseUrl: "https://api.x.ai/v1",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 0,
			output: 0,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 200000,
		maxTokens: 128000,
	} satisfies Model<"openai-codex-responses">,
} as const;
